image: docker:latest

services:
  - docker:dind

stages:
  - build

.build:
  stage: build
  script:
    - docker build --build-arg=coq_image="coqorg/${CI_JOB_NAME}" --pull -t demo .

coq:8.4:
  extends: .build

coq:8.5:
  extends: .build

coq:8.6:
  extends: .build

coq:8.7:
  extends: .build

coq:8.8:
  extends: .build

coq:dev:
  extends: .build
